url: https://spcbrcks.com
# baseurl: /agency-jekyll-theme/

# Site settings
title: SpaceBricks
email: contact-us@spcbrcks.com
description: "Expert software development, blockchain solutions, and cybersecurity services. We deliver high-quality digital products and secure systems tailored to your business goals."


# Team names, titles and social links
people:
- name: Alexandros Andreou
  pic: alex
  position: Cyber Security and Blockchain Engineering
  social:
    - title: twitter
      url: https://x.com/alex10791
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #
    - title: linkedin
      url: https://www.linkedin.com/in/alex10791/
    # - title: google-plus
    #   url: #
    - title: globe
      url : https://alex.cy

- name: Theodoros Danos
  pic: theo
  position: Cyber Security and Blockchain Engineering
  social:
    - title: twitter
      url: https://x.com/fand0mas
    - title: linkedin
      url: https://www.linkedin.com/in/theodoros-danos-b17a97206/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Mehmet Ali 70
  - line: Larnaca, 6026, Cyprus

# Build settings
markdown: kramdown
permalink: pretty